version: '3.5'

services:

  mongo:
    container_name: mongoDB
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27017:27017"
    networks:
      - local

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,s3
    volumes:
      - "../aws/localstack.sh:/docker-entrypoint-initaws.d/make-services.sh"
    networks:
      - local

networks:
  local:
    driver: bridge